import json
import yaml
from openai import OpenAI
from src.engine.state_machine import RPMStateMachine
from src.engine.interceptor import SafetyInterceptor
from src.tools.registry import ToolRegistry

class RPMAgent:
    def __init__(self, env: str = "local"):
        with open("configs/model.yaml", "r") as f:
            config = yaml.safe_load(f)

        endpoint = config["endpoints"][env]
        self.client = OpenAI(
            base_url=endpoint["api_base"],
            api_key="sk-local-dev" # Dummy key for Ollama/vLLM
        )
        self.model_id = endpoint["model_id"]
        self.temperature = endpoint["temperature"]
        self.max_tokens = endpoint["max_tokens"]

        # Maintain conversational history
        self.messages = []

    def process_turn(
        self,
        user_input: str,
        dfa: RPMStateMachine,
        registry: ToolRegistry,
        interceptor: SafetyInterceptor
    ) -> str:
        # 1. Out-Of-Band Safety Check (The Intercept)
        safety_check = interceptor.inspect(user_input)
        if safety_check.is_red_flag:
            dfa.force_escalation()
            # Execute escalation directly via registry bypassing LLM hallucination risk
            escalation_result = registry.execute_tool("escalate_to_nurse", {"reason": safety_check.reason})
            return f"EMERGENCY PROTOCOL ENGAGED: {escalation_result['message']}"

        # Append user message to history
        self.messages.append({"role": "user", "content": user_input})

        # 2. Get Deterministic Context from DFA
        system_prompt, allowed_tools = dfa.get_context()
        tool_schemas = registry.get_tool_schemas(allowed_tools)

        # Build dynamic system message injected ONLY for this specific turn
        current_system_msg = {"role": "system", "content": system_prompt}
        messages_for_llm = [current_system_msg] + self.messages

        # 3. Execute LLM Call
        api_kwargs = {
            "model": self.model_id,
            "messages": messages_for_llm,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        # Only inject the tools parameter if the current state permits them
        if tool_schemas:
            api_kwargs["tools"] = tool_schemas
            api_kwargs["tool_choice"] = "auto"

        try:
            response = self.client.chat.completions.create(**api_kwargs)
            response_msg = response.choices[0].message
        except Exception as e:
            return f"[System Error] LLM Backend disconnected or failed: {str(e)}"

        # 4. Process Tool Calls (JSON Validation & Execution)
        if response_msg.tool_calls:
            for tool_call in response_msg.tool_calls:
                tool_name = tool_call.function.name
                try:
                    tool_args = json.loads(tool_call.function.arguments)
                except json.JSONDecodeError:
                    return f"[System Error] LLM generated malformed JSON (JavaScript Object Notation) for {tool_name}."

                # Execute strictly via Pydantic registry
                execution_result = registry.execute_tool(tool_name, tool_args)

                # Update DFA state
                transition_msg = dfa.process_tool_execution(tool_name, execution_result)

                # Append assistant's structural decision to memory
                self.messages.append({
                    "role": "assistant",
                    "content": f"Executed {tool_name}: {execution_result['message']}"
                })

                return f"🔧 Tool Executed: {tool_name}\nResult: {execution_result['message']}\n{transition_msg}"

        # 5. Process Standard Text Response
        if response_msg.content:
            self.messages.append({"role": "assistant", "content": response_msg.content})
            return response_msg.content

        return "[System] No valid response generated by the LLM."
